# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b1f58647a1ebb8577b1d5135eb30ea9a4c4376788e52e96348382c9c49feed909c5b9000668a09b5c02787a57fec3741fe56595c1181694fa647e31e66b633f
  facebook_id: <%= ENV["FACEBOOK_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>

test:
  secret_key_base: a5fbc484b93c23bf861bc73d507baca84bfd4701b50c7da6dee80889d6719e317ceeb547932b44f5a682111b3d9775d4fbba4eb6abf7c39dc83a50be0beeb554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_id: <%= ENV["FACEBOOK_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
