# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Dvd.create(title: "Grown Ups", year: 2010, genre: "comedy", rated: "PG-13", published: true)
Dvd.create(title: "Grown Ups 2", year: 2013, genre: "comedy", rated: "PG-13", published: true)
Dvd.create(title: "Just Go with It", year: 2011, genre: "comedy, romance", rated: "PG-13", published: true)
Dvd.create(title: "The Hangover", year: 2009, genre: "comedy", rated: "R", published: true)
Dvd.create(title: "The Hangover Part II", year: 2011, genre: "comedy", rated: "R", published: true)
Dvd.create(title: "The Hangover Part III", year: 2013, genre: "comedy", rated: "R", published: true)
Dvd.create(title: "The Campaign", year: 2012, genre: "comedy", rated: "R", published: true)
Dvd.create(title: "Due Date", year: 2010, genre: "comedy", rated: "R", published: true)
Dvd.create(title: "Forrest Gump", year: 1994, genre: "drama, romance", rated: "PG-13", published: true)
Dvd.create(title: "Saving Private Ryan", year: 1998, genre: "action, drama, war", rated: "R", published: true)
Dvd.create(title: "Back to the Future", year: 1985, genre: "adventure, comedy, sci_fi", rated: "PG", published: true)
Dvd.create(title: "The Lion King", year: 1994, genre: "animation, adventure, drama, family, musical", rated: "G", published: true)
Dvd.create(title: "The Dark Knight Rises", year: 2012, genre: "action, thriller", rated: "PG-13", published: true)
Dvd.create(title: "WALL-E", year: 2008, genre: "animation, adventure, sci_fi", rated: "G", published: true)
Dvd.create(title: "Toy Story 3", year: 2010, genre: "animation, adventure, comedy, family, fantasy", rated: "G", published: true)
Dvd.create(title: "Toy Story", year: 1995, genre: "animation, adventure, comedy, family, fantasy", rated: "G", published: true)
Dvd.create(title: "Toy Story 2", year: 1999, genre: "animation, adventure, comedy, family, fantasy", rated: "G", published: true)
Dvd.create(title: "Monsters, Inc.", year: 2001, genre: "animation, adventure, comedy, family, fantasy", rated: "G", published: true)
Dvd.create(title: "Finding Nemo", year: 2003, genre: "animation, adventure, comedy, family", rated: "G", published: true)
Dvd.create(title: "Cars", year: 2006, genre: "animation, adventure, comedy, family, sport", rated: "G", published: true)
Dvd.create(title: "The Incredibles", year: 2004, genre: "animation, action, adventure, family", rated: "PG", published: true)
Dvd.create(title: "Shrek", year: 2001, genre: "animation, adventure, comedy, family, fantasy", rated: "PG", published: true)
Dvd.create(title: "Beauty and the Beast", year: 1991, genre: "animation, family, fantasy, musical, romance", rated: "G", published: true)
Dvd.create(title: "Ratatouille", year: 2007, genre: "animation, comedy, family, fantasy", rated: "G", published: true)
Dvd.create(title: "Braveheart", year: 1995, genre: "action, biography, drama, history, war", rated: "R", published: true)
Dvd.create(title: "Singin' in the Rain", year: 1952, genre: "comedy, musical, romance", rated: "PG", published: true)
Dvd.create(title: "Monty Python and the Holy Grail", year: 1975, genre: "adventure, comedy, fantasy", rated: "PG", published: true)
Dvd.create(title: "Inglourious Basterds", year: 2009, genre: "adventure, drama, war", rated: "R", published: true)
Dvd.create(title: "Batman Begins", year: 2005, genre: "action, adventure", rated: "PG-13", published: true)
Dvd.create(title: "Up", year: 2009, genre: "animation, adventure, comedy, family", rated: "PG", published: true)
Dvd.create(title: "How to Train Your Dragon", year: 2010, genre: "animation, adventure, family, fantasy", rated: "PG", published: true)
Dvd.create(title: "How to Train Your Dragon 2", year: 2014, genre: "animation, action, adventure, comedy, family, fantasy", rated: "PG", published: true)
Dvd.create(title: "Frozen", year: 2013, genre: "animation, adventure, comedy, family, fantasy, musical", rated: "PG", published: true)
Dvd.create(title: "Gone with the Wind", year: 1939, genre: "drama, romance, war", rated: "G", published: true)
Dvd.create(title: "Ice Age", year: 2002, genre: "animation, adventure, comedy, family", rated: "PG", published: true)
Dvd.create(title: "The Princess Bride", year: 1987, genre: "adventure, comedy, family, fantasy, romance", rated: "PG", published: true)
Dvd.create(title: "The Wizard of Oz", year: 1939, genre: "adventure, family, fantasy, musical", rated: "G", published: true)
Dvd.create(title: "It's a Wonderful Life", year: 1946, genre: "drama, family, fantasy", rated: "G", published: true)
Dvd.create(title: "Mary Poppins", year: 1964, genre: "comedy, family, fantasy, musical", rated: "G", published: true)
Dvd.create(title: "Snow White and the Seven Dwarfs", year: 1937, genre: "animation, family, fantasy, musical, romance", rated: "G", published: true)
Dvd.create(title: "Willy Wonka & the Chocolate Factory", year: 1971, genre: "family, fantasy, musical", rated: "G", published: true)
Dvd.create(title: "Guardians of the Galaxy", year: 2014, genre: "action, adventure, sci_fi", rated: "PG-13", published: true)
Dvd.create(title: "The Bourne Ultimatum", year: 2007, genre: "action, thriller", rated: "PG-13", published: true)
Dvd.create(title: "The Bourne Supremacy", year: 2004, genre: "action, thriller", rated: "PG-13", published: true)
Dvd.create(title: "The Bourne Identity", year: 2002, genre: "action, mystery, thriller", rated: "PG-13", published: true)
Dvd.create(title: "The Bourne Legacy", year: 2012, genre: "action, adventure, mystery, thriller", rated: "PG-13", published: true)
Dvd.create(title: "Die Hard", year: 1988, genre: "action, thriller", rated: "R", published: true)
Dvd.create(title: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003, genre: "adventure, fantasy", rated: "PG-13", published: true)
Dvd.create(title: "The Terminator", year: 1984, genre: "action, sci_fi", rated: "R", published: true)
Dvd.create(title: "Jurassic Park", year: 1993, genre: "adventure, sci_fi, thriller", rated: "PG-13", published: true)
Dvd.create(title: "Step Brothers", year: 2008, genre: "comedy", rated: "R", published: true)
Dvd.create(title: "Anchorman: The Legend of Ron Burgundy", year: 2004, genre: "comedy", rated: "PG-13", published: true)
Dvd.create(title: "Anchorman 2: The Legend Continues", year: 2013, genre: "comedy", rated: "R", published: true)
Dvd.create(title: "The Other Guys", year: 2010, genre: "action, comedy, crime", rated: "PG-13", published: true)
Dvd.create(title: "The Internship", year: 2013, genre: "comedy", rated: "PG-13", published: true)
Dvd.create(title: "Talladega Nights: The Ballad of Ricky Bobby", year: 2006, genre: "action, comedy, sport", rated: "PG-13", published: true)
Dvd.create(title: "Elf", year: 2003, genre: "comedy, family, fantasy, romance", rated: "PG", published: true)
Dvd.create(title: "Zoolander", year: 2001, genre: "comedy", rated: "PG-13", published: true)
Dvd.create(title: "Groundhog Day", year: 1993, genre: "comedy, drama, fantasy, romance", rated: "PG", published: true)
Dvd.create(title: "Cars 2", year: 2011, genre: "animation, adventure, comedy, family", rated: "G", published: true)
